apiVersion: v1
entries:
  stage-platform:
  - apiVersion: v1
    appVersion: V1.0
    created: "2020-11-10T15:07:33.3014776Z"
    description: Naast deze JSON rest API is er ook een [graphql](/graphql) interface
      beschikbaar.
    digest: 16d5dbb1d0633dc73cada63a3e8ad6745f2f2960eaa51ee036d68cbd724ca0df
    home: www.stage-platform.com
    icon: www.stage-platform.com
    name: stage-platform
    urls:
    - stage-platform-0.1.0.tgz
    version: 0.1.0
generated: "2020-11-10T15:07:33.2930085Z"
